### ISSUE TITLE
Minecraft v1.12.2

### ISSUE THREAD

**Issue by qmnl** [SirWindfield/vanilla-tools#15]
Can we get a release for Minecraft v1.12.2. On Curse there is no release for 1.12.2, and trying the 1.12 release in Minecraft 1.12.2 does not work:

```
kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
	at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:45)
	at kotlin.jvm.internal.ClassReference.getObjectInstance(ClassReference.kt:43)
	at de.zerotask.minecraft.tooltweaks.language.KotlinAdapter.getNewInstance(KotlinAdapter.kt:33)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:586)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Danke schonmal im Vorraus xD

**Comment by mainrs** [comment]
The 1.12.x jar can run on any minecraft version. I didn't have the time to actually publish the 1.13 version. I'm quite busy with university right now. I implemented one new feature, config file synching. Server owners can npw just specify the items in the server config and it gets synched top the client when connecting.

I'm 100% certain that we (my friends and myself) played on 1.12.2 back then. The error says kotlin-reflect.jar is not on the classpath. Did you install Shadow's Forgelin too? 

I moved the codebase to Kotlin some time ago (I'm still not sure why. Maybe I just wanted toy try it out :smile:). As the minecraftforge page lists:

> If you run a version newer than or equal to 1.0.7, you will need Shadowfact's Forgelin installed too! It will install automatically for modpacks created within the Twitch App.

Pretty sure you forgot to install that mod too! It provides the needed libraries (jar files) for mods written in Kotlin. 1.0.8 is actually ported back to Java to circumvent a configuration bug that hasn't been fixed in Forge for half a year. 

Pretty sure I can spent two or three hours on monday to push 1.0.8 out there :smile:. As I am not playing MC lately a lot I kind of lost the motivation to keep this mod up-to-date. I'll make sure to fix bugs and port over to new versions but won't implement new features unless I get a PR or I actually go back to MC and need the feature ^^.

**Comment by qmnl** [comment]
I used the Twitch App to setup a modpack with mc 1.12.2. When search for this mod, it didn't get listed. That's why I installed it manually. I now also installed Shadow's Forgelin and it works. Thank for your quick help.

**Comment by mainrs** [comment]
It didn't get listed? Strange... I need to take a look at this. I know that I used to add it over Twitch too and it automatically fetched the dependency too back then. Maybe they changed the metadata file format or some other stuff. Thanks for letting me know. And nno problem :smile:.

**Comment by qmnl** [comment]
BTW: I made a blacklist for https://teamcofh.com/docs/thermal-foundation/: https://gist.github.com/simonmeusel/b84a873cde9d0ae5eaf7a454dd7261e3 , If you want to put a link of it anywhere :)

**Comment by mainrs** [comment]
Having an index or a modpack list might actually be a cool idea. Mind linking me to the modpack? Is it tech/magic based? Maybe a mix?

**Comment by qmnl** [comment]
I sent the link (https://teamcofh.com/docs/thermal-foundation/), the curse page is https://minecraft.curseforge.com/projects/thermal-foundation.

It is mainly tech based. It adds a bunch of ores (and the corresponding tools), which then can be used by https://minecraft.curseforge.com/projects/thermalexpansion.
